apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 8.6.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 10m
  values:
    externalDatabase:
      enabled: true
      type: mysql

    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 150Gi
      storageClassName: oci-bv

    nextcloud:
      extraEnv:
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "cloud.hanhela.org"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: OVERWRITEHOST
          value: "cloud.hanhela.org"
        - name: TRUSTED_PROXIES
          value: "10.0.0.0/8"

    externalRedis:
      enabled: true
      host: redis-master
      port: 6379
      database: 0
      password: ""

  valuesFrom:
    - kind: Secret
      name: nextcloud-db
      valuesKey: MYSQL_HOST
      targetPath: externalDatabase.host
    - kind: Secret
      name: nextcloud-db
      valuesKey: MYSQL_PORT
      targetPath: externalDatabase.port
    - kind: Secret
      name: nextcloud-db
      valuesKey: MYSQL_DATABASE
      targetPath: externalDatabase.database
    - kind: Secret
      name: nextcloud-db
      valuesKey: MYSQL_USER
      targetPath: externalDatabase.username
    - kind: Secret
      name: nextcloud-db
      valuesKey: MYSQL_PASSWORD
      targetPath: externalDatabase.password


