apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 8.6.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 10m
  values:
    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 100Gi
      storageClassName: oci-bv-uhp

    env:
      - name: MYSQL_HOST
        valueFrom:
          secretKeyRef:
            name: nextcloud-db
            key: MYSQL_HOST
      - name: MYSQL_PORT
        valueFrom:
          secretKeyRef:
            name: nextcloud-db
            key: MYSQL_PORT
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: nextcloud-db
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: nextcloud-db
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: nextcloud-db
            key: MYSQL_PASSWORD
      - name: NEXTCLOUD_TRUSTED_DOMAINS
        value: "cloud.hanhela.org"
      - name: OVERWRITEPROTOCOL
        value: "https"
      - name: OVERWRITEHOST
        value: "cloud.hanhela.org"
      - name: TRUSTED_PROXIES
        value: "10.0.0.0/8"
      - name: REDIS_HOST
        value: nextcloud-redis-master
      - name: REDIS_HOST_PORT
        value: "6379"
