apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  storageClassName: oci-bv-uhp
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
