apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  interval: 12h
  releaseName: redis
  targetNamespace: nextcloud

  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: nextcloud

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    replica:
      replicaCount: 0

