apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud-redis
  namespace: nextcloud
spec:
  releaseName: redis
  targetNamespace: nextcloud
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: nextcloud
  interval: 12h
    #version:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    replicaCount: 0
