apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-redis
  namespace: nextcloud
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  tag: "24.0.0"
