apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m 
  chart:
    spec:
      chart: ingress-nginx
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h 
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 5m
  values:
    controller:
      replicaCount: 1
      ingressClassResource:
        name: nginx
        default: true
      service:
        type: LoadBalancer
        annotations:
          oci.oraclecloud.com/load-balancer-type: "nlb"
          oci-network-load-balancer.oraclecloud.com/security-list-management-mode: "None"
        ports:
          http: 80
          https: 443 
      ports:
        http: 80
        https: 443 
    admissionWebhooks:
      enabled: false

