apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hanhela-org-wildcard
  namespace: whoami
spec:
  secretName: hanhela-org-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  commonName: hanhela.org
  dnsNames:
    - hanhela.org
    - '*.hanhela.org'
