apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mumble
  namespace: mumble
spec:
  interval: 30m
  url: https://github.com/JuniorJPDJ/charts/tree/master/charts/mumble-server
