apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: JuniorJPDJ-mumble
  namespace: mumble
spec:
  interval: 12h
  url: https://github.com/JuniorJPDJ/charts/tree/master/charts/mumble-server
  ref:
    tag: "0.1.31"
  
